(define (domain peg-solitaire)
  (:requirements :strips :typing :negative-preconditions :equality)

  (:types
    board
    location
    peg
    move
  )

  (:predicates
    (has-location ?b - board ?l - location)
    (peg-at-location ?p - peg ?l - location)
    (location-empty ?l - location)
    (location-on-board ?l - location ?b - board)
    (peg-on-board ?p - peg ?b - board)
    (peg-eliminated ?p - peg)
    (move-initiated ?m - move)
    (move-continued ?m - move)
    (move-ended ?m - move)
    (move-from-location ?m - move ?l - location)
    (move-over-peg ?m - move ?p - peg)
    (move-to-location ?m - move ?l - location)
  )

  (:action initiate-move
    :parameters (?m - move ?p - peg ?from - location ?over - peg ?mid - location ?to - location ?b - board)
    :precondition (and
      (peg-at-location ?p ?from)
      (peg-on-board ?p ?b)
      (peg-at-location ?over ?mid)
      (peg-on-board ?over ?b)
      (location-empty ?to)
      (location-on-board ?from ?b)
      (location-on-board ?mid ?b)
      (location-on-board ?to ?b)
      (has-location ?b ?from)
      (has-location ?b ?mid)
      (has-location ?b ?to)
      (not (peg-eliminated ?over))
      (not (move-initiated ?m))
      (not (move-continued ?m))
      (not (move-ended ?m))
      (not (location-empty ?from))
      (not (location-empty ?mid))
    )
    :effect (and
      (not (peg-at-location ?p ?from))
      (location-empty ?from)
      (peg-at-location ?p ?to)
      (not (location-empty ?to))
      (not (peg-at-location ?over ?mid))
      (location-empty ?mid)
      (peg-eliminated ?over)
      (not (peg-on-board ?over ?b))
      (move-initiated ?m)
      (move-from-location ?m ?from)
      (move-over-peg ?m ?over)
      (move-to-location ?m ?to)
    )
  )

  (:action continue-move
    :parameters (?m - move ?p - peg ?from - location ?over - peg ?mid - location ?to - location ?b - board)
    :precondition (and
      (move-initiated ?m)
      (not (move-continued ?m))
      (not (move-ended ?m))
      (peg-at-location ?p ?from)
      (peg-on-board ?p ?b)
      (peg-at-location ?over ?mid)
      (peg-on-board ?over ?b)
      (location-empty ?to)
      (location-on-board ?from ?b)
      (location-on-board ?mid ?b)
      (location-on-board ?to ?b)
      (has-location ?b ?from)
      (has-location ?b ?mid)
      (has-location ?b ?to)
      (not (peg-eliminated ?over))
      (not (location-empty ?from))
      (not (location-empty ?mid))
    )
    :effect (and
      (not (peg-at-location ?p ?from))
      (location-empty ?from)
      (peg-at-location ?p ?to)
      (not (location-empty ?to))
      (not (peg-at-location ?over ?mid))
      (location-empty ?mid)
      (peg-eliminated ?over)
      (not (peg-on-board ?over ?b))
      (move-continued ?m)
      (move-from-location ?m ?from)
      (move-over-peg ?m ?over)
      (move-to-location ?m ?to)
    )
  )

  (:action end-move
    :parameters (?m - move)
    :precondition (and
      (move-initiated ?m)
      (not (move-ended ?m))
    )
    :effect (and
      (move-ended ?m)
    )
  )

  (:action undo-move
    :parameters (?m - move ?p - peg ?from - location ?over - peg ?mid - location ?to - location ?b - board)
    :precondition (and
      (move-initiated ?m)
      (peg-at-location ?p ?to)
      (peg-eliminated ?over)
      (location-empty ?from)
      (location-empty ?mid)
      (location-on-board ?from ?b)
      (location-on-board ?mid ?b)
      (location-on-board ?to ?b)
      (has-location ?b ?from)
      (has-location ?b ?mid)
      (has-location ?b ?to)
    )
    :effect (and
      (not (peg-at-location ?p ?to))
      (location-empty ?to)
      (peg-at-location ?p ?from)
      (not (location-empty ?from))
      (peg-at-location ?over ?mid)
      (not (location-empty ?mid))
      (not (peg-eliminated ?over))
      (peg-on-board ?over ?b)
      (not (move-initiated ?m))
      (not (move-continued ?m))
      (not (move-ended ?m))
      (not (move-from-location ?m ?from))
      (not (move-over-peg ?m ?over))
      (not (move-to-location ?m ?to))
    )
  )
)
