(define (domain mydomain)
  (:requirements :typing :fluents)
  (:types robot minebot robot cell item lift rock ore environment)
  (:predicates
    (robot-is-moving)
    (robot-has-item)
    (robot-battery-level)
    (minebot-is-navigating)
    (minebot-is-mining)
    (minebot-fuel-level)
    (cell-is-occupied)
    (cell-has-item)
    (item-is-picked-up)
    (item-is-put-down)
    (lift-is-operational)
    (lift-has-minebot)
    (rock-is-broken)
    (rock-has-ore)
    (ore-is-mined)
    (ore-is-processed)
    (environment-has-obstacle)
    (environment-has-resource)
  )
  (:action move
    :parameters (?mb - minebot ?from - cell ?to - cell)
    :precondition (and (minebot-is-navigating ?mb) (cell-is-occupied ?from) (not (cell-is-occupied ?to)))
    :effect (and (not (cell-is-occupied ?from)) (cell-is-occupied ?to))
  )
  (:action pick-up
    :parameters (?mb - minebot ?item - item ?from - cell)
    :precondition (and (minebot-is-navigating ?mb) (cell-is-occupied ?from) (robot-has-item ?item) (not (item-is-picked-up ?item)))
    :effect (and (not (robot-has-item ?item)) (item-is-picked-up ?item))
  )
  (:action put-down
    :parameters (?mb - minebot ?item - item ?to - cell)
    :precondition (and (minebot-is-navigating ?mb) (cell-is-occupied ?to) (item-is-picked-up ?item) (not (robot-has-item ?item)))
    :effect (and (not (item-is-picked-up ?item)) (robot-has-item ?item))
  )
  (:action use-lift
    :parameters (?mb - minebot ?lift - lift ?from - cell ?to - cell)
    :precondition (and (minebot-is-navigating ?mb) (cell-is-occupied ?from) (lift-is-operational ?lift) (lift-has-minebot ?lift) (not (cell-is-occupied ?to)))
    :effect (and (not (cell-is-occupied ?from)) (cell-is-occupied ?to))
  )
  (:action break-rock
    :parameters (?mb - minebot ?rock - rock ?cell - cell)
    :precondition (and (minebot-is-navigating ?mb) (cell-is-occupied ?cell) (not (rock-is-broken ?rock)))
    :effect (and (not (rock-has-ore ?rock)) (rock-is-broken ?rock))
  )
  (:action mine-ore
    :parameters (?mb - minebot ?ore - ore ?rock - rock)
    :precondition (and (minebot-is-navigating ?mb) (rock-is-broken ?rock) (not (ore-is-mined ?ore)))
    :effect (and (not (rock-has-ore ?rock)) (ore-is-mined ?ore))
  )
  (:action process-ore
    :parameters (?mb - minebot ?ore - ore)
    :precondition (and (minebot-is-navigating ?mb) (ore-is-mined ?ore) (not (ore-is-processed ?ore)))
    :effect (ore-is-processed ?ore)
  )
)