# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions

import baml_py

from . import stream_types, types
from .runtime import DoNotUseDirectlyCallManager, BamlCallOptions

class LlmResponseParser:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    def ExtractActionsAzure(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.ActionsResult:
        result = self.__options.merge_options(baml_options).parse_response(function_name="ExtractActionsAzure", llm_response=llm_response, mode="request")
        return typing.cast(types.ActionsResult, result)

    def ExtractActionsDeep(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.ActionsResult:
        result = self.__options.merge_options(baml_options).parse_response(function_name="ExtractActionsDeep", llm_response=llm_response, mode="request")
        return typing.cast(types.ActionsResult, result)

    def ExtractActionsGemini(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.ActionsResult:
        result = self.__options.merge_options(baml_options).parse_response(function_name="ExtractActionsGemini", llm_response=llm_response, mode="request")
        return typing.cast(types.ActionsResult, result)

    def ExtractAttributesAzure(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.AttributesResult:
        result = self.__options.merge_options(baml_options).parse_response(function_name="ExtractAttributesAzure", llm_response=llm_response, mode="request")
        return typing.cast(types.AttributesResult, result)

    def ExtractAttributesDeep(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.AttributesResult:
        result = self.__options.merge_options(baml_options).parse_response(function_name="ExtractAttributesDeep", llm_response=llm_response, mode="request")
        return typing.cast(types.AttributesResult, result)

    def ExtractAttributesGemini(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.AttributesResult:
        result = self.__options.merge_options(baml_options).parse_response(function_name="ExtractAttributesGemini", llm_response=llm_response, mode="request")
        return typing.cast(types.AttributesResult, result)

    def ExtractGoalAzure(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.GoalResult:
        result = self.__options.merge_options(baml_options).parse_response(function_name="ExtractGoalAzure", llm_response=llm_response, mode="request")
        return typing.cast(types.GoalResult, result)

    def ExtractGoalDeep(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.GoalResult:
        result = self.__options.merge_options(baml_options).parse_response(function_name="ExtractGoalDeep", llm_response=llm_response, mode="request")
        return typing.cast(types.GoalResult, result)

    def ExtractGoalGemini(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.GoalResult:
        result = self.__options.merge_options(baml_options).parse_response(function_name="ExtractGoalGemini", llm_response=llm_response, mode="request")
        return typing.cast(types.GoalResult, result)

    def ExtractInitialStateAzure(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.InitialStateResult:
        result = self.__options.merge_options(baml_options).parse_response(function_name="ExtractInitialStateAzure", llm_response=llm_response, mode="request")
        return typing.cast(types.InitialStateResult, result)

    def ExtractInitialStateDeep(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.InitialStateResult:
        result = self.__options.merge_options(baml_options).parse_response(function_name="ExtractInitialStateDeep", llm_response=llm_response, mode="request")
        return typing.cast(types.InitialStateResult, result)

    def ExtractInitialStateGemini(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.InitialStateResult:
        result = self.__options.merge_options(baml_options).parse_response(function_name="ExtractInitialStateGemini", llm_response=llm_response, mode="request")
        return typing.cast(types.InitialStateResult, result)

    def ExtractObjectTypesAzure(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.ObjectTypesResult:
        result = self.__options.merge_options(baml_options).parse_response(function_name="ExtractObjectTypesAzure", llm_response=llm_response, mode="request")
        return typing.cast(types.ObjectTypesResult, result)

    def ExtractObjectTypesDeep(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.ObjectTypesResult:
        result = self.__options.merge_options(baml_options).parse_response(function_name="ExtractObjectTypesDeep", llm_response=llm_response, mode="request")
        return typing.cast(types.ObjectTypesResult, result)

    def ExtractObjectTypesGemini(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.ObjectTypesResult:
        result = self.__options.merge_options(baml_options).parse_response(function_name="ExtractObjectTypesGemini", llm_response=llm_response, mode="request")
        return typing.cast(types.ObjectTypesResult, result)

    def ExtractProblemObjectsAzure(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.ObjectsResult:
        result = self.__options.merge_options(baml_options).parse_response(function_name="ExtractProblemObjectsAzure", llm_response=llm_response, mode="request")
        return typing.cast(types.ObjectsResult, result)

    def ExtractProblemObjectsDeep(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.ObjectsResult:
        result = self.__options.merge_options(baml_options).parse_response(function_name="ExtractProblemObjectsDeep", llm_response=llm_response, mode="request")
        return typing.cast(types.ObjectsResult, result)

    def ExtractProblemObjectsGemini(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.ObjectsResult:
        result = self.__options.merge_options(baml_options).parse_response(function_name="ExtractProblemObjectsGemini", llm_response=llm_response, mode="request")
        return typing.cast(types.ObjectsResult, result)

    def ExtractResume(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.Resume:
        result = self.__options.merge_options(baml_options).parse_response(function_name="ExtractResume", llm_response=llm_response, mode="request")
        return typing.cast(types.Resume, result)

    def GeneratePDDLDomainAzure(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.PDDLDomainResult:
        result = self.__options.merge_options(baml_options).parse_response(function_name="GeneratePDDLDomainAzure", llm_response=llm_response, mode="request")
        return typing.cast(types.PDDLDomainResult, result)

    def GeneratePDDLDomainDeep(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.PDDLDomainResult:
        result = self.__options.merge_options(baml_options).parse_response(function_name="GeneratePDDLDomainDeep", llm_response=llm_response, mode="request")
        return typing.cast(types.PDDLDomainResult, result)

    def GeneratePDDLDomainGemini(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.PDDLDomainResult:
        result = self.__options.merge_options(baml_options).parse_response(function_name="GeneratePDDLDomainGemini", llm_response=llm_response, mode="request")
        return typing.cast(types.PDDLDomainResult, result)

    def GeneratePDDLProblemAzure(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.PDDLProblemResult:
        result = self.__options.merge_options(baml_options).parse_response(function_name="GeneratePDDLProblemAzure", llm_response=llm_response, mode="request")
        return typing.cast(types.PDDLProblemResult, result)

    def GeneratePDDLProblemDeep(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.PDDLProblemResult:
        result = self.__options.merge_options(baml_options).parse_response(function_name="GeneratePDDLProblemDeep", llm_response=llm_response, mode="request")
        return typing.cast(types.PDDLProblemResult, result)

    def GeneratePDDLProblemGemini(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.PDDLProblemResult:
        result = self.__options.merge_options(baml_options).parse_response(function_name="GeneratePDDLProblemGemini", llm_response=llm_response, mode="request")
        return typing.cast(types.PDDLProblemResult, result)

    def RefineAndAggregateDomainAzure(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.RefinedActionsResult:
        result = self.__options.merge_options(baml_options).parse_response(function_name="RefineAndAggregateDomainAzure", llm_response=llm_response, mode="request")
        return typing.cast(types.RefinedActionsResult, result)

    def RefineAndAggregateDomainDeep(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.RefinedActionsResult:
        result = self.__options.merge_options(baml_options).parse_response(function_name="RefineAndAggregateDomainDeep", llm_response=llm_response, mode="request")
        return typing.cast(types.RefinedActionsResult, result)

    def RefineAndAggregateDomainGemini(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.RefinedActionsResult:
        result = self.__options.merge_options(baml_options).parse_response(function_name="RefineAndAggregateDomainGemini", llm_response=llm_response, mode="request")
        return typing.cast(types.RefinedActionsResult, result)

    

class LlmStreamParser:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    def ExtractActionsAzure(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.ActionsResult:
        result = self.__options.merge_options(baml_options).parse_response(function_name="ExtractActionsAzure", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.ActionsResult, result)

    def ExtractActionsDeep(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.ActionsResult:
        result = self.__options.merge_options(baml_options).parse_response(function_name="ExtractActionsDeep", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.ActionsResult, result)

    def ExtractActionsGemini(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.ActionsResult:
        result = self.__options.merge_options(baml_options).parse_response(function_name="ExtractActionsGemini", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.ActionsResult, result)

    def ExtractAttributesAzure(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.AttributesResult:
        result = self.__options.merge_options(baml_options).parse_response(function_name="ExtractAttributesAzure", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.AttributesResult, result)

    def ExtractAttributesDeep(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.AttributesResult:
        result = self.__options.merge_options(baml_options).parse_response(function_name="ExtractAttributesDeep", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.AttributesResult, result)

    def ExtractAttributesGemini(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.AttributesResult:
        result = self.__options.merge_options(baml_options).parse_response(function_name="ExtractAttributesGemini", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.AttributesResult, result)

    def ExtractGoalAzure(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.GoalResult:
        result = self.__options.merge_options(baml_options).parse_response(function_name="ExtractGoalAzure", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.GoalResult, result)

    def ExtractGoalDeep(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.GoalResult:
        result = self.__options.merge_options(baml_options).parse_response(function_name="ExtractGoalDeep", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.GoalResult, result)

    def ExtractGoalGemini(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.GoalResult:
        result = self.__options.merge_options(baml_options).parse_response(function_name="ExtractGoalGemini", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.GoalResult, result)

    def ExtractInitialStateAzure(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.InitialStateResult:
        result = self.__options.merge_options(baml_options).parse_response(function_name="ExtractInitialStateAzure", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.InitialStateResult, result)

    def ExtractInitialStateDeep(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.InitialStateResult:
        result = self.__options.merge_options(baml_options).parse_response(function_name="ExtractInitialStateDeep", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.InitialStateResult, result)

    def ExtractInitialStateGemini(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.InitialStateResult:
        result = self.__options.merge_options(baml_options).parse_response(function_name="ExtractInitialStateGemini", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.InitialStateResult, result)

    def ExtractObjectTypesAzure(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.ObjectTypesResult:
        result = self.__options.merge_options(baml_options).parse_response(function_name="ExtractObjectTypesAzure", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.ObjectTypesResult, result)

    def ExtractObjectTypesDeep(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.ObjectTypesResult:
        result = self.__options.merge_options(baml_options).parse_response(function_name="ExtractObjectTypesDeep", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.ObjectTypesResult, result)

    def ExtractObjectTypesGemini(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.ObjectTypesResult:
        result = self.__options.merge_options(baml_options).parse_response(function_name="ExtractObjectTypesGemini", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.ObjectTypesResult, result)

    def ExtractProblemObjectsAzure(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.ObjectsResult:
        result = self.__options.merge_options(baml_options).parse_response(function_name="ExtractProblemObjectsAzure", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.ObjectsResult, result)

    def ExtractProblemObjectsDeep(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.ObjectsResult:
        result = self.__options.merge_options(baml_options).parse_response(function_name="ExtractProblemObjectsDeep", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.ObjectsResult, result)

    def ExtractProblemObjectsGemini(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.ObjectsResult:
        result = self.__options.merge_options(baml_options).parse_response(function_name="ExtractProblemObjectsGemini", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.ObjectsResult, result)

    def ExtractResume(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.Resume:
        result = self.__options.merge_options(baml_options).parse_response(function_name="ExtractResume", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.Resume, result)

    def GeneratePDDLDomainAzure(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.PDDLDomainResult:
        result = self.__options.merge_options(baml_options).parse_response(function_name="GeneratePDDLDomainAzure", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.PDDLDomainResult, result)

    def GeneratePDDLDomainDeep(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.PDDLDomainResult:
        result = self.__options.merge_options(baml_options).parse_response(function_name="GeneratePDDLDomainDeep", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.PDDLDomainResult, result)

    def GeneratePDDLDomainGemini(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.PDDLDomainResult:
        result = self.__options.merge_options(baml_options).parse_response(function_name="GeneratePDDLDomainGemini", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.PDDLDomainResult, result)

    def GeneratePDDLProblemAzure(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.PDDLProblemResult:
        result = self.__options.merge_options(baml_options).parse_response(function_name="GeneratePDDLProblemAzure", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.PDDLProblemResult, result)

    def GeneratePDDLProblemDeep(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.PDDLProblemResult:
        result = self.__options.merge_options(baml_options).parse_response(function_name="GeneratePDDLProblemDeep", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.PDDLProblemResult, result)

    def GeneratePDDLProblemGemini(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.PDDLProblemResult:
        result = self.__options.merge_options(baml_options).parse_response(function_name="GeneratePDDLProblemGemini", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.PDDLProblemResult, result)

    def RefineAndAggregateDomainAzure(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.RefinedActionsResult:
        result = self.__options.merge_options(baml_options).parse_response(function_name="RefineAndAggregateDomainAzure", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.RefinedActionsResult, result)

    def RefineAndAggregateDomainDeep(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.RefinedActionsResult:
        result = self.__options.merge_options(baml_options).parse_response(function_name="RefineAndAggregateDomainDeep", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.RefinedActionsResult, result)

    def RefineAndAggregateDomainGemini(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.RefinedActionsResult:
        result = self.__options.merge_options(baml_options).parse_response(function_name="RefineAndAggregateDomainGemini", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.RefinedActionsResult, result)

    