# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions
from pydantic import BaseModel, ConfigDict

import baml_py

from . import types

StreamStateValueT = typing.TypeVar('StreamStateValueT')
class StreamState(BaseModel, typing.Generic[StreamStateValueT]):
    value: StreamStateValueT
    state: typing_extensions.Literal["Pending", "Incomplete", "Complete"]
# #########################################################################
# Generated classes (23)
# #########################################################################

class Action(BaseModel):
    name: typing.Optional[str] = None
    actor: typing.Optional[str] = None
    parameters: typing.List["Parameters"]
    preconditions: typing.List["Precondition"]
    effects: typing.List["Effect"]
    description: typing.Optional[str] = None

class ActionsResult(BaseModel):
    actions: typing.List["Action"]

class Attribute(BaseModel):
    name: typing.Optional[str] = None
    type: typing.Optional[str] = None
    description: typing.Optional[str] = None

class AttributesResult(BaseModel):
    types_with_attributes: typing.List["TypeAttributes"]

class Effect(BaseModel):
    attribute: typing.Optional[str] = None
    change: typing.Optional[str] = None

class GoalCondition(BaseModel):
    object_name: typing.Optional[str] = None
    attribute: typing.Optional[str] = None
    required_value: typing.Optional[str] = None
    explanation: typing.Optional[str] = None

class GoalRelation(BaseModel):
    relation_type: typing.Optional[str] = None
    object1: typing.Optional[str] = None
    object2: typing.Optional[str] = None
    explanation: typing.Optional[str] = None

class GoalResult(BaseModel):
    conditions: typing.List["GoalCondition"]
    relations: typing.List["GoalRelation"]
    goal_summary: typing.Optional[str] = None

class InitialFact(BaseModel):
    object_name: typing.Optional[str] = None
    attribute: typing.Optional[str] = None
    value: typing.Optional[str] = None
    explanation: typing.Optional[str] = None

class InitialRelation(BaseModel):
    relation_type: typing.Optional[str] = None
    object1: typing.Optional[str] = None
    object2: typing.Optional[str] = None
    explanation: typing.Optional[str] = None

class InitialStateResult(BaseModel):
    facts: typing.List["InitialFact"]
    relations: typing.List["InitialRelation"]

class ObjectTypeHierarchy(BaseModel):
    name: typing.Optional[str] = None
    parent_type: typing.Optional[str] = None
    description: typing.Optional[str] = None

class ObjectTypesResult(BaseModel):
    types: typing.List["ObjectTypeHierarchy"]

class ObjectsResult(BaseModel):
    objects: typing.List["ProblemObject"]

class PDDLDomainResult(BaseModel):
    domain_name: typing.Optional[str] = None
    pddl_code: typing.Optional[str] = None
    explanation: typing.Optional[str] = None

class PDDLProblemResult(BaseModel):
    problem_name: typing.Optional[str] = None
    domain_name: typing.Optional[str] = None
    pddl_code: typing.Optional[str] = None
    explanation: typing.Optional[str] = None

class Parameters(BaseModel):
    name: typing.Optional[str] = None
    type: typing.Optional[str] = None

class Precondition(BaseModel):
    attribute: typing.Optional[str] = None
    condition: typing.Optional[str] = None

class ProblemObject(BaseModel):
    name: typing.Optional[str] = None
    type: typing.Optional[str] = None
    description: typing.Optional[str] = None

class RefinedAction(BaseModel):
    name: typing.Optional[str] = None
    description: typing.Optional[str] = None
    actor: typing.Optional[str] = None
    parameters: typing.List["Parameters"]
    preconditions: typing.List["Precondition"]
    effects: typing.List["Effect"]
    requires_adl: typing.Optional[str] = None

class RefinedActionsResult(BaseModel):
    actions: typing.List["RefinedAction"]

class Resume(BaseModel):
    name: typing.Optional[str] = None
    email: typing.Optional[str] = None
    experience: typing.List[str]
    skills: typing.List[str]

class TypeAttributes(BaseModel):
    type_name: typing.Optional[str] = None
    attributes: typing.List["Attribute"]

# #########################################################################
# Generated type aliases (0)
# #########################################################################
