# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions
import baml_py

from . import stream_types, types, type_builder
from .parser import LlmResponseParser, LlmStreamParser
from .runtime import DoNotUseDirectlyCallManager, BamlCallOptions
from .globals import DO_NOT_USE_DIRECTLY_UNLESS_YOU_KNOW_WHAT_YOURE_DOING_RUNTIME as __runtime__

class BamlSyncClient:
    __options: DoNotUseDirectlyCallManager
    __stream_client: "BamlStreamClient"
    __http_request: "BamlHttpRequestClient"
    __http_stream_request: "BamlHttpStreamRequestClient"
    __llm_response_parser: LlmResponseParser
    __llm_stream_parser: LlmStreamParser

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options
        self.__stream_client = BamlStreamClient(options)
        self.__http_request = BamlHttpRequestClient(options)
        self.__http_stream_request = BamlHttpStreamRequestClient(options)
        self.__llm_response_parser = LlmResponseParser(options)
        self.__llm_stream_parser = LlmStreamParser(options)

    def __getstate__(self):
        # Return state needed for pickling
        return {"options": self.__options}

    def __setstate__(self, state):
        # Restore state from pickling
        self.__options = state["options"]
        self.__stream_client = BamlStreamClient(self.__options)
        self.__http_request = BamlHttpRequestClient(self.__options)
        self.__http_stream_request = BamlHttpStreamRequestClient(self.__options)
        self.__llm_response_parser = LlmResponseParser(self.__options)
        self.__llm_stream_parser = LlmStreamParser(self.__options)

    def with_options(self,
        tb: typing.Optional[type_builder.TypeBuilder] = None,
        client_registry: typing.Optional[baml_py.baml_py.ClientRegistry] = None,
        collector: typing.Optional[typing.Union[baml_py.baml_py.Collector, typing.List[baml_py.baml_py.Collector]]] = None,
        env: typing.Optional[typing.Dict[str, typing.Optional[str]]] = None,
        tags: typing.Optional[typing.Dict[str, str]] = None,
        on_tick: typing.Optional[typing.Callable[[str, baml_py.baml_py.FunctionLog], None]] = None,
    ) -> "BamlSyncClient":
        options: BamlCallOptions = {}
        if tb is not None:
            options["tb"] = tb
        if client_registry is not None:
            options["client_registry"] = client_registry
        if collector is not None:
            options["collector"] = collector
        if env is not None:
            options["env"] = env
        if tags is not None:
            options["tags"] = tags
        if on_tick is not None:
            options["on_tick"] = on_tick
        return BamlSyncClient(self.__options.merge_options(options))

    @property
    def stream(self):
      return self.__stream_client

    @property
    def request(self):
      return self.__http_request

    @property
    def stream_request(self):
      return self.__http_stream_request

    @property
    def parse(self):
      return self.__llm_response_parser

    @property
    def parse_stream(self):
      return self.__llm_stream_parser
    
    def ExtractActionsAzure(self, domain_description: str,object_types: str,object_attributes: str,
        baml_options: BamlCallOptions = {},
    ) -> types.ActionsResult:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            stream = self.stream.ExtractActionsAzure(domain_description=domain_description,object_types=object_types,object_attributes=object_attributes,
                baml_options=baml_options)
            return stream.get_final_response()
        else:
            # Original non-streaming code
            result = self.__options.merge_options(baml_options).call_function_sync(function_name="ExtractActionsAzure", args={
                "domain_description": domain_description,"object_types": object_types,"object_attributes": object_attributes,
            })
            return typing.cast(types.ActionsResult, result.cast_to(types, types, stream_types, False, __runtime__))
    def ExtractActionsDeep(self, domain_description: str,object_types: str,object_attributes: str,
        baml_options: BamlCallOptions = {},
    ) -> types.ActionsResult:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            stream = self.stream.ExtractActionsDeep(domain_description=domain_description,object_types=object_types,object_attributes=object_attributes,
                baml_options=baml_options)
            return stream.get_final_response()
        else:
            # Original non-streaming code
            result = self.__options.merge_options(baml_options).call_function_sync(function_name="ExtractActionsDeep", args={
                "domain_description": domain_description,"object_types": object_types,"object_attributes": object_attributes,
            })
            return typing.cast(types.ActionsResult, result.cast_to(types, types, stream_types, False, __runtime__))
    def ExtractActionsGemini(self, domain_description: str,object_types: str,object_attributes: str,
        baml_options: BamlCallOptions = {},
    ) -> types.ActionsResult:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            stream = self.stream.ExtractActionsGemini(domain_description=domain_description,object_types=object_types,object_attributes=object_attributes,
                baml_options=baml_options)
            return stream.get_final_response()
        else:
            # Original non-streaming code
            result = self.__options.merge_options(baml_options).call_function_sync(function_name="ExtractActionsGemini", args={
                "domain_description": domain_description,"object_types": object_types,"object_attributes": object_attributes,
            })
            return typing.cast(types.ActionsResult, result.cast_to(types, types, stream_types, False, __runtime__))
    def ExtractAttributesAzure(self, object_types: str,domain_description: str,
        baml_options: BamlCallOptions = {},
    ) -> types.AttributesResult:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            stream = self.stream.ExtractAttributesAzure(object_types=object_types,domain_description=domain_description,
                baml_options=baml_options)
            return stream.get_final_response()
        else:
            # Original non-streaming code
            result = self.__options.merge_options(baml_options).call_function_sync(function_name="ExtractAttributesAzure", args={
                "object_types": object_types,"domain_description": domain_description,
            })
            return typing.cast(types.AttributesResult, result.cast_to(types, types, stream_types, False, __runtime__))
    def ExtractAttributesDeep(self, object_types: str,domain_description: str,
        baml_options: BamlCallOptions = {},
    ) -> types.AttributesResult:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            stream = self.stream.ExtractAttributesDeep(object_types=object_types,domain_description=domain_description,
                baml_options=baml_options)
            return stream.get_final_response()
        else:
            # Original non-streaming code
            result = self.__options.merge_options(baml_options).call_function_sync(function_name="ExtractAttributesDeep", args={
                "object_types": object_types,"domain_description": domain_description,
            })
            return typing.cast(types.AttributesResult, result.cast_to(types, types, stream_types, False, __runtime__))
    def ExtractAttributesGemini(self, object_types: str,domain_description: str,
        baml_options: BamlCallOptions = {},
    ) -> types.AttributesResult:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            stream = self.stream.ExtractAttributesGemini(object_types=object_types,domain_description=domain_description,
                baml_options=baml_options)
            return stream.get_final_response()
        else:
            # Original non-streaming code
            result = self.__options.merge_options(baml_options).call_function_sync(function_name="ExtractAttributesGemini", args={
                "object_types": object_types,"domain_description": domain_description,
            })
            return typing.cast(types.AttributesResult, result.cast_to(types, types, stream_types, False, __runtime__))
    def ExtractGoalAzure(self, problem_description: str,problem_objects: str,initial_state: str,domain_description: str,
        baml_options: BamlCallOptions = {},
    ) -> types.GoalResult:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            stream = self.stream.ExtractGoalAzure(problem_description=problem_description,problem_objects=problem_objects,initial_state=initial_state,domain_description=domain_description,
                baml_options=baml_options)
            return stream.get_final_response()
        else:
            # Original non-streaming code
            result = self.__options.merge_options(baml_options).call_function_sync(function_name="ExtractGoalAzure", args={
                "problem_description": problem_description,"problem_objects": problem_objects,"initial_state": initial_state,"domain_description": domain_description,
            })
            return typing.cast(types.GoalResult, result.cast_to(types, types, stream_types, False, __runtime__))
    def ExtractGoalDeep(self, problem_description: str,problem_objects: str,initial_state: str,domain_description: str,
        baml_options: BamlCallOptions = {},
    ) -> types.GoalResult:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            stream = self.stream.ExtractGoalDeep(problem_description=problem_description,problem_objects=problem_objects,initial_state=initial_state,domain_description=domain_description,
                baml_options=baml_options)
            return stream.get_final_response()
        else:
            # Original non-streaming code
            result = self.__options.merge_options(baml_options).call_function_sync(function_name="ExtractGoalDeep", args={
                "problem_description": problem_description,"problem_objects": problem_objects,"initial_state": initial_state,"domain_description": domain_description,
            })
            return typing.cast(types.GoalResult, result.cast_to(types, types, stream_types, False, __runtime__))
    def ExtractGoalGemini(self, problem_description: str,problem_objects: str,initial_state: str,domain_description: str,
        baml_options: BamlCallOptions = {},
    ) -> types.GoalResult:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            stream = self.stream.ExtractGoalGemini(problem_description=problem_description,problem_objects=problem_objects,initial_state=initial_state,domain_description=domain_description,
                baml_options=baml_options)
            return stream.get_final_response()
        else:
            # Original non-streaming code
            result = self.__options.merge_options(baml_options).call_function_sync(function_name="ExtractGoalGemini", args={
                "problem_description": problem_description,"problem_objects": problem_objects,"initial_state": initial_state,"domain_description": domain_description,
            })
            return typing.cast(types.GoalResult, result.cast_to(types, types, stream_types, False, __runtime__))
    def ExtractInitialStateAzure(self, problem_description: str,problem_objects: str,object_attributes: str,domain_description: str,
        baml_options: BamlCallOptions = {},
    ) -> types.InitialStateResult:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            stream = self.stream.ExtractInitialStateAzure(problem_description=problem_description,problem_objects=problem_objects,object_attributes=object_attributes,domain_description=domain_description,
                baml_options=baml_options)
            return stream.get_final_response()
        else:
            # Original non-streaming code
            result = self.__options.merge_options(baml_options).call_function_sync(function_name="ExtractInitialStateAzure", args={
                "problem_description": problem_description,"problem_objects": problem_objects,"object_attributes": object_attributes,"domain_description": domain_description,
            })
            return typing.cast(types.InitialStateResult, result.cast_to(types, types, stream_types, False, __runtime__))
    def ExtractInitialStateDeep(self, problem_description: str,problem_objects: str,object_attributes: str,domain_description: str,
        baml_options: BamlCallOptions = {},
    ) -> types.InitialStateResult:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            stream = self.stream.ExtractInitialStateDeep(problem_description=problem_description,problem_objects=problem_objects,object_attributes=object_attributes,domain_description=domain_description,
                baml_options=baml_options)
            return stream.get_final_response()
        else:
            # Original non-streaming code
            result = self.__options.merge_options(baml_options).call_function_sync(function_name="ExtractInitialStateDeep", args={
                "problem_description": problem_description,"problem_objects": problem_objects,"object_attributes": object_attributes,"domain_description": domain_description,
            })
            return typing.cast(types.InitialStateResult, result.cast_to(types, types, stream_types, False, __runtime__))
    def ExtractInitialStateGemini(self, problem_description: str,problem_objects: str,object_attributes: str,domain_description: str,
        baml_options: BamlCallOptions = {},
    ) -> types.InitialStateResult:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            stream = self.stream.ExtractInitialStateGemini(problem_description=problem_description,problem_objects=problem_objects,object_attributes=object_attributes,domain_description=domain_description,
                baml_options=baml_options)
            return stream.get_final_response()
        else:
            # Original non-streaming code
            result = self.__options.merge_options(baml_options).call_function_sync(function_name="ExtractInitialStateGemini", args={
                "problem_description": problem_description,"problem_objects": problem_objects,"object_attributes": object_attributes,"domain_description": domain_description,
            })
            return typing.cast(types.InitialStateResult, result.cast_to(types, types, stream_types, False, __runtime__))
    def ExtractObjectTypesAzure(self, domain_description: str,
        baml_options: BamlCallOptions = {},
    ) -> types.ObjectTypesResult:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            stream = self.stream.ExtractObjectTypesAzure(domain_description=domain_description,
                baml_options=baml_options)
            return stream.get_final_response()
        else:
            # Original non-streaming code
            result = self.__options.merge_options(baml_options).call_function_sync(function_name="ExtractObjectTypesAzure", args={
                "domain_description": domain_description,
            })
            return typing.cast(types.ObjectTypesResult, result.cast_to(types, types, stream_types, False, __runtime__))
    def ExtractObjectTypesDeep(self, domain_description: str,
        baml_options: BamlCallOptions = {},
    ) -> types.ObjectTypesResult:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            stream = self.stream.ExtractObjectTypesDeep(domain_description=domain_description,
                baml_options=baml_options)
            return stream.get_final_response()
        else:
            # Original non-streaming code
            result = self.__options.merge_options(baml_options).call_function_sync(function_name="ExtractObjectTypesDeep", args={
                "domain_description": domain_description,
            })
            return typing.cast(types.ObjectTypesResult, result.cast_to(types, types, stream_types, False, __runtime__))
    def ExtractObjectTypesGemini(self, domain_description: str,
        baml_options: BamlCallOptions = {},
    ) -> types.ObjectTypesResult:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            stream = self.stream.ExtractObjectTypesGemini(domain_description=domain_description,
                baml_options=baml_options)
            return stream.get_final_response()
        else:
            # Original non-streaming code
            result = self.__options.merge_options(baml_options).call_function_sync(function_name="ExtractObjectTypesGemini", args={
                "domain_description": domain_description,
            })
            return typing.cast(types.ObjectTypesResult, result.cast_to(types, types, stream_types, False, __runtime__))
    def ExtractProblemObjectsAzure(self, problem_description: str,object_types: str,domain_description: str,
        baml_options: BamlCallOptions = {},
    ) -> types.ObjectsResult:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            stream = self.stream.ExtractProblemObjectsAzure(problem_description=problem_description,object_types=object_types,domain_description=domain_description,
                baml_options=baml_options)
            return stream.get_final_response()
        else:
            # Original non-streaming code
            result = self.__options.merge_options(baml_options).call_function_sync(function_name="ExtractProblemObjectsAzure", args={
                "problem_description": problem_description,"object_types": object_types,"domain_description": domain_description,
            })
            return typing.cast(types.ObjectsResult, result.cast_to(types, types, stream_types, False, __runtime__))
    def ExtractProblemObjectsDeep(self, problem_description: str,object_types: str,domain_description: str,
        baml_options: BamlCallOptions = {},
    ) -> types.ObjectsResult:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            stream = self.stream.ExtractProblemObjectsDeep(problem_description=problem_description,object_types=object_types,domain_description=domain_description,
                baml_options=baml_options)
            return stream.get_final_response()
        else:
            # Original non-streaming code
            result = self.__options.merge_options(baml_options).call_function_sync(function_name="ExtractProblemObjectsDeep", args={
                "problem_description": problem_description,"object_types": object_types,"domain_description": domain_description,
            })
            return typing.cast(types.ObjectsResult, result.cast_to(types, types, stream_types, False, __runtime__))
    def ExtractProblemObjectsGemini(self, problem_description: str,object_types: str,domain_description: str,
        baml_options: BamlCallOptions = {},
    ) -> types.ObjectsResult:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            stream = self.stream.ExtractProblemObjectsGemini(problem_description=problem_description,object_types=object_types,domain_description=domain_description,
                baml_options=baml_options)
            return stream.get_final_response()
        else:
            # Original non-streaming code
            result = self.__options.merge_options(baml_options).call_function_sync(function_name="ExtractProblemObjectsGemini", args={
                "problem_description": problem_description,"object_types": object_types,"domain_description": domain_description,
            })
            return typing.cast(types.ObjectsResult, result.cast_to(types, types, stream_types, False, __runtime__))
    def ExtractResume(self, resume: str,
        baml_options: BamlCallOptions = {},
    ) -> types.Resume:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            stream = self.stream.ExtractResume(resume=resume,
                baml_options=baml_options)
            return stream.get_final_response()
        else:
            # Original non-streaming code
            result = self.__options.merge_options(baml_options).call_function_sync(function_name="ExtractResume", args={
                "resume": resume,
            })
            return typing.cast(types.Resume, result.cast_to(types, types, stream_types, False, __runtime__))
    def GeneratePDDLDomainAzure(self, domain_description: str,object_nl: str,attributes_nl: str,actions_nl: str,
        baml_options: BamlCallOptions = {},
    ) -> types.PDDLDomainResult:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            stream = self.stream.GeneratePDDLDomainAzure(domain_description=domain_description,object_nl=object_nl,attributes_nl=attributes_nl,actions_nl=actions_nl,
                baml_options=baml_options)
            return stream.get_final_response()
        else:
            # Original non-streaming code
            result = self.__options.merge_options(baml_options).call_function_sync(function_name="GeneratePDDLDomainAzure", args={
                "domain_description": domain_description,"object_nl": object_nl,"attributes_nl": attributes_nl,"actions_nl": actions_nl,
            })
            return typing.cast(types.PDDLDomainResult, result.cast_to(types, types, stream_types, False, __runtime__))
    def GeneratePDDLDomainDeep(self, domain_description: str,object_nl: str,attributes_nl: str,actions_nl: str,
        baml_options: BamlCallOptions = {},
    ) -> types.PDDLDomainResult:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            stream = self.stream.GeneratePDDLDomainDeep(domain_description=domain_description,object_nl=object_nl,attributes_nl=attributes_nl,actions_nl=actions_nl,
                baml_options=baml_options)
            return stream.get_final_response()
        else:
            # Original non-streaming code
            result = self.__options.merge_options(baml_options).call_function_sync(function_name="GeneratePDDLDomainDeep", args={
                "domain_description": domain_description,"object_nl": object_nl,"attributes_nl": attributes_nl,"actions_nl": actions_nl,
            })
            return typing.cast(types.PDDLDomainResult, result.cast_to(types, types, stream_types, False, __runtime__))
    def GeneratePDDLDomainGemini(self, domain_description: str,object_nl: str,attributes_nl: str,actions_nl: str,
        baml_options: BamlCallOptions = {},
    ) -> types.PDDLDomainResult:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            stream = self.stream.GeneratePDDLDomainGemini(domain_description=domain_description,object_nl=object_nl,attributes_nl=attributes_nl,actions_nl=actions_nl,
                baml_options=baml_options)
            return stream.get_final_response()
        else:
            # Original non-streaming code
            result = self.__options.merge_options(baml_options).call_function_sync(function_name="GeneratePDDLDomainGemini", args={
                "domain_description": domain_description,"object_nl": object_nl,"attributes_nl": attributes_nl,"actions_nl": actions_nl,
            })
            return typing.cast(types.PDDLDomainResult, result.cast_to(types, types, stream_types, False, __runtime__))
    def GeneratePDDLProblemAzure(self, problem_description: str,domain_pddl_code: str,objects_baml: str,init_state_baml: str,goal_state_baml: str,
        baml_options: BamlCallOptions = {},
    ) -> types.PDDLProblemResult:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            stream = self.stream.GeneratePDDLProblemAzure(problem_description=problem_description,domain_pddl_code=domain_pddl_code,objects_baml=objects_baml,init_state_baml=init_state_baml,goal_state_baml=goal_state_baml,
                baml_options=baml_options)
            return stream.get_final_response()
        else:
            # Original non-streaming code
            result = self.__options.merge_options(baml_options).call_function_sync(function_name="GeneratePDDLProblemAzure", args={
                "problem_description": problem_description,"domain_pddl_code": domain_pddl_code,"objects_baml": objects_baml,"init_state_baml": init_state_baml,"goal_state_baml": goal_state_baml,
            })
            return typing.cast(types.PDDLProblemResult, result.cast_to(types, types, stream_types, False, __runtime__))
    def GeneratePDDLProblemDeep(self, problem_description: str,domain_pddl_code: str,objects_baml: str,init_state_baml: str,goal_state_baml: str,
        baml_options: BamlCallOptions = {},
    ) -> types.PDDLProblemResult:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            stream = self.stream.GeneratePDDLProblemDeep(problem_description=problem_description,domain_pddl_code=domain_pddl_code,objects_baml=objects_baml,init_state_baml=init_state_baml,goal_state_baml=goal_state_baml,
                baml_options=baml_options)
            return stream.get_final_response()
        else:
            # Original non-streaming code
            result = self.__options.merge_options(baml_options).call_function_sync(function_name="GeneratePDDLProblemDeep", args={
                "problem_description": problem_description,"domain_pddl_code": domain_pddl_code,"objects_baml": objects_baml,"init_state_baml": init_state_baml,"goal_state_baml": goal_state_baml,
            })
            return typing.cast(types.PDDLProblemResult, result.cast_to(types, types, stream_types, False, __runtime__))
    def GeneratePDDLProblemGemini(self, problem_description: str,domain_pddl_code: str,objects_baml: str,init_state_baml: str,goal_state_baml: str,
        baml_options: BamlCallOptions = {},
    ) -> types.PDDLProblemResult:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            stream = self.stream.GeneratePDDLProblemGemini(problem_description=problem_description,domain_pddl_code=domain_pddl_code,objects_baml=objects_baml,init_state_baml=init_state_baml,goal_state_baml=goal_state_baml,
                baml_options=baml_options)
            return stream.get_final_response()
        else:
            # Original non-streaming code
            result = self.__options.merge_options(baml_options).call_function_sync(function_name="GeneratePDDLProblemGemini", args={
                "problem_description": problem_description,"domain_pddl_code": domain_pddl_code,"objects_baml": objects_baml,"init_state_baml": init_state_baml,"goal_state_baml": goal_state_baml,
            })
            return typing.cast(types.PDDLProblemResult, result.cast_to(types, types, stream_types, False, __runtime__))
    def RefineAndAggregateDomainAzure(self, domain_description: str,object_types: str,attributes: str,actions_list: str,
        baml_options: BamlCallOptions = {},
    ) -> types.RefinedActionsResult:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            stream = self.stream.RefineAndAggregateDomainAzure(domain_description=domain_description,object_types=object_types,attributes=attributes,actions_list=actions_list,
                baml_options=baml_options)
            return stream.get_final_response()
        else:
            # Original non-streaming code
            result = self.__options.merge_options(baml_options).call_function_sync(function_name="RefineAndAggregateDomainAzure", args={
                "domain_description": domain_description,"object_types": object_types,"attributes": attributes,"actions_list": actions_list,
            })
            return typing.cast(types.RefinedActionsResult, result.cast_to(types, types, stream_types, False, __runtime__))
    def RefineAndAggregateDomainDeep(self, domain_description: str,object_types: str,attributes: str,actions_list: str,
        baml_options: BamlCallOptions = {},
    ) -> types.RefinedActionsResult:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            stream = self.stream.RefineAndAggregateDomainDeep(domain_description=domain_description,object_types=object_types,attributes=attributes,actions_list=actions_list,
                baml_options=baml_options)
            return stream.get_final_response()
        else:
            # Original non-streaming code
            result = self.__options.merge_options(baml_options).call_function_sync(function_name="RefineAndAggregateDomainDeep", args={
                "domain_description": domain_description,"object_types": object_types,"attributes": attributes,"actions_list": actions_list,
            })
            return typing.cast(types.RefinedActionsResult, result.cast_to(types, types, stream_types, False, __runtime__))
    def RefineAndAggregateDomainGemini(self, domain_description: str,object_types: str,attributes: str,actions_list: str,
        baml_options: BamlCallOptions = {},
    ) -> types.RefinedActionsResult:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            stream = self.stream.RefineAndAggregateDomainGemini(domain_description=domain_description,object_types=object_types,attributes=attributes,actions_list=actions_list,
                baml_options=baml_options)
            return stream.get_final_response()
        else:
            # Original non-streaming code
            result = self.__options.merge_options(baml_options).call_function_sync(function_name="RefineAndAggregateDomainGemini", args={
                "domain_description": domain_description,"object_types": object_types,"attributes": attributes,"actions_list": actions_list,
            })
            return typing.cast(types.RefinedActionsResult, result.cast_to(types, types, stream_types, False, __runtime__))
    


class BamlStreamClient:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    def ExtractActionsAzure(self, domain_description: str,object_types: str,object_attributes: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlSyncStream[stream_types.ActionsResult, types.ActionsResult]:
        ctx, result = self.__options.merge_options(baml_options).create_sync_stream(function_name="ExtractActionsAzure", args={
            "domain_description": domain_description,"object_types": object_types,"object_attributes": object_attributes,
        })
        return baml_py.BamlSyncStream[stream_types.ActionsResult, types.ActionsResult](
          result,
          lambda x: typing.cast(stream_types.ActionsResult, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(types.ActionsResult, x.cast_to(types, types, stream_types, False, __runtime__)),
          ctx,
        )
    def ExtractActionsDeep(self, domain_description: str,object_types: str,object_attributes: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlSyncStream[stream_types.ActionsResult, types.ActionsResult]:
        ctx, result = self.__options.merge_options(baml_options).create_sync_stream(function_name="ExtractActionsDeep", args={
            "domain_description": domain_description,"object_types": object_types,"object_attributes": object_attributes,
        })
        return baml_py.BamlSyncStream[stream_types.ActionsResult, types.ActionsResult](
          result,
          lambda x: typing.cast(stream_types.ActionsResult, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(types.ActionsResult, x.cast_to(types, types, stream_types, False, __runtime__)),
          ctx,
        )
    def ExtractActionsGemini(self, domain_description: str,object_types: str,object_attributes: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlSyncStream[stream_types.ActionsResult, types.ActionsResult]:
        ctx, result = self.__options.merge_options(baml_options).create_sync_stream(function_name="ExtractActionsGemini", args={
            "domain_description": domain_description,"object_types": object_types,"object_attributes": object_attributes,
        })
        return baml_py.BamlSyncStream[stream_types.ActionsResult, types.ActionsResult](
          result,
          lambda x: typing.cast(stream_types.ActionsResult, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(types.ActionsResult, x.cast_to(types, types, stream_types, False, __runtime__)),
          ctx,
        )
    def ExtractAttributesAzure(self, object_types: str,domain_description: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlSyncStream[stream_types.AttributesResult, types.AttributesResult]:
        ctx, result = self.__options.merge_options(baml_options).create_sync_stream(function_name="ExtractAttributesAzure", args={
            "object_types": object_types,"domain_description": domain_description,
        })
        return baml_py.BamlSyncStream[stream_types.AttributesResult, types.AttributesResult](
          result,
          lambda x: typing.cast(stream_types.AttributesResult, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(types.AttributesResult, x.cast_to(types, types, stream_types, False, __runtime__)),
          ctx,
        )
    def ExtractAttributesDeep(self, object_types: str,domain_description: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlSyncStream[stream_types.AttributesResult, types.AttributesResult]:
        ctx, result = self.__options.merge_options(baml_options).create_sync_stream(function_name="ExtractAttributesDeep", args={
            "object_types": object_types,"domain_description": domain_description,
        })
        return baml_py.BamlSyncStream[stream_types.AttributesResult, types.AttributesResult](
          result,
          lambda x: typing.cast(stream_types.AttributesResult, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(types.AttributesResult, x.cast_to(types, types, stream_types, False, __runtime__)),
          ctx,
        )
    def ExtractAttributesGemini(self, object_types: str,domain_description: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlSyncStream[stream_types.AttributesResult, types.AttributesResult]:
        ctx, result = self.__options.merge_options(baml_options).create_sync_stream(function_name="ExtractAttributesGemini", args={
            "object_types": object_types,"domain_description": domain_description,
        })
        return baml_py.BamlSyncStream[stream_types.AttributesResult, types.AttributesResult](
          result,
          lambda x: typing.cast(stream_types.AttributesResult, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(types.AttributesResult, x.cast_to(types, types, stream_types, False, __runtime__)),
          ctx,
        )
    def ExtractGoalAzure(self, problem_description: str,problem_objects: str,initial_state: str,domain_description: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlSyncStream[stream_types.GoalResult, types.GoalResult]:
        ctx, result = self.__options.merge_options(baml_options).create_sync_stream(function_name="ExtractGoalAzure", args={
            "problem_description": problem_description,"problem_objects": problem_objects,"initial_state": initial_state,"domain_description": domain_description,
        })
        return baml_py.BamlSyncStream[stream_types.GoalResult, types.GoalResult](
          result,
          lambda x: typing.cast(stream_types.GoalResult, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(types.GoalResult, x.cast_to(types, types, stream_types, False, __runtime__)),
          ctx,
        )
    def ExtractGoalDeep(self, problem_description: str,problem_objects: str,initial_state: str,domain_description: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlSyncStream[stream_types.GoalResult, types.GoalResult]:
        ctx, result = self.__options.merge_options(baml_options).create_sync_stream(function_name="ExtractGoalDeep", args={
            "problem_description": problem_description,"problem_objects": problem_objects,"initial_state": initial_state,"domain_description": domain_description,
        })
        return baml_py.BamlSyncStream[stream_types.GoalResult, types.GoalResult](
          result,
          lambda x: typing.cast(stream_types.GoalResult, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(types.GoalResult, x.cast_to(types, types, stream_types, False, __runtime__)),
          ctx,
        )
    def ExtractGoalGemini(self, problem_description: str,problem_objects: str,initial_state: str,domain_description: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlSyncStream[stream_types.GoalResult, types.GoalResult]:
        ctx, result = self.__options.merge_options(baml_options).create_sync_stream(function_name="ExtractGoalGemini", args={
            "problem_description": problem_description,"problem_objects": problem_objects,"initial_state": initial_state,"domain_description": domain_description,
        })
        return baml_py.BamlSyncStream[stream_types.GoalResult, types.GoalResult](
          result,
          lambda x: typing.cast(stream_types.GoalResult, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(types.GoalResult, x.cast_to(types, types, stream_types, False, __runtime__)),
          ctx,
        )
    def ExtractInitialStateAzure(self, problem_description: str,problem_objects: str,object_attributes: str,domain_description: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlSyncStream[stream_types.InitialStateResult, types.InitialStateResult]:
        ctx, result = self.__options.merge_options(baml_options).create_sync_stream(function_name="ExtractInitialStateAzure", args={
            "problem_description": problem_description,"problem_objects": problem_objects,"object_attributes": object_attributes,"domain_description": domain_description,
        })
        return baml_py.BamlSyncStream[stream_types.InitialStateResult, types.InitialStateResult](
          result,
          lambda x: typing.cast(stream_types.InitialStateResult, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(types.InitialStateResult, x.cast_to(types, types, stream_types, False, __runtime__)),
          ctx,
        )
    def ExtractInitialStateDeep(self, problem_description: str,problem_objects: str,object_attributes: str,domain_description: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlSyncStream[stream_types.InitialStateResult, types.InitialStateResult]:
        ctx, result = self.__options.merge_options(baml_options).create_sync_stream(function_name="ExtractInitialStateDeep", args={
            "problem_description": problem_description,"problem_objects": problem_objects,"object_attributes": object_attributes,"domain_description": domain_description,
        })
        return baml_py.BamlSyncStream[stream_types.InitialStateResult, types.InitialStateResult](
          result,
          lambda x: typing.cast(stream_types.InitialStateResult, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(types.InitialStateResult, x.cast_to(types, types, stream_types, False, __runtime__)),
          ctx,
        )
    def ExtractInitialStateGemini(self, problem_description: str,problem_objects: str,object_attributes: str,domain_description: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlSyncStream[stream_types.InitialStateResult, types.InitialStateResult]:
        ctx, result = self.__options.merge_options(baml_options).create_sync_stream(function_name="ExtractInitialStateGemini", args={
            "problem_description": problem_description,"problem_objects": problem_objects,"object_attributes": object_attributes,"domain_description": domain_description,
        })
        return baml_py.BamlSyncStream[stream_types.InitialStateResult, types.InitialStateResult](
          result,
          lambda x: typing.cast(stream_types.InitialStateResult, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(types.InitialStateResult, x.cast_to(types, types, stream_types, False, __runtime__)),
          ctx,
        )
    def ExtractObjectTypesAzure(self, domain_description: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlSyncStream[stream_types.ObjectTypesResult, types.ObjectTypesResult]:
        ctx, result = self.__options.merge_options(baml_options).create_sync_stream(function_name="ExtractObjectTypesAzure", args={
            "domain_description": domain_description,
        })
        return baml_py.BamlSyncStream[stream_types.ObjectTypesResult, types.ObjectTypesResult](
          result,
          lambda x: typing.cast(stream_types.ObjectTypesResult, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(types.ObjectTypesResult, x.cast_to(types, types, stream_types, False, __runtime__)),
          ctx,
        )
    def ExtractObjectTypesDeep(self, domain_description: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlSyncStream[stream_types.ObjectTypesResult, types.ObjectTypesResult]:
        ctx, result = self.__options.merge_options(baml_options).create_sync_stream(function_name="ExtractObjectTypesDeep", args={
            "domain_description": domain_description,
        })
        return baml_py.BamlSyncStream[stream_types.ObjectTypesResult, types.ObjectTypesResult](
          result,
          lambda x: typing.cast(stream_types.ObjectTypesResult, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(types.ObjectTypesResult, x.cast_to(types, types, stream_types, False, __runtime__)),
          ctx,
        )
    def ExtractObjectTypesGemini(self, domain_description: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlSyncStream[stream_types.ObjectTypesResult, types.ObjectTypesResult]:
        ctx, result = self.__options.merge_options(baml_options).create_sync_stream(function_name="ExtractObjectTypesGemini", args={
            "domain_description": domain_description,
        })
        return baml_py.BamlSyncStream[stream_types.ObjectTypesResult, types.ObjectTypesResult](
          result,
          lambda x: typing.cast(stream_types.ObjectTypesResult, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(types.ObjectTypesResult, x.cast_to(types, types, stream_types, False, __runtime__)),
          ctx,
        )
    def ExtractProblemObjectsAzure(self, problem_description: str,object_types: str,domain_description: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlSyncStream[stream_types.ObjectsResult, types.ObjectsResult]:
        ctx, result = self.__options.merge_options(baml_options).create_sync_stream(function_name="ExtractProblemObjectsAzure", args={
            "problem_description": problem_description,"object_types": object_types,"domain_description": domain_description,
        })
        return baml_py.BamlSyncStream[stream_types.ObjectsResult, types.ObjectsResult](
          result,
          lambda x: typing.cast(stream_types.ObjectsResult, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(types.ObjectsResult, x.cast_to(types, types, stream_types, False, __runtime__)),
          ctx,
        )
    def ExtractProblemObjectsDeep(self, problem_description: str,object_types: str,domain_description: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlSyncStream[stream_types.ObjectsResult, types.ObjectsResult]:
        ctx, result = self.__options.merge_options(baml_options).create_sync_stream(function_name="ExtractProblemObjectsDeep", args={
            "problem_description": problem_description,"object_types": object_types,"domain_description": domain_description,
        })
        return baml_py.BamlSyncStream[stream_types.ObjectsResult, types.ObjectsResult](
          result,
          lambda x: typing.cast(stream_types.ObjectsResult, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(types.ObjectsResult, x.cast_to(types, types, stream_types, False, __runtime__)),
          ctx,
        )
    def ExtractProblemObjectsGemini(self, problem_description: str,object_types: str,domain_description: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlSyncStream[stream_types.ObjectsResult, types.ObjectsResult]:
        ctx, result = self.__options.merge_options(baml_options).create_sync_stream(function_name="ExtractProblemObjectsGemini", args={
            "problem_description": problem_description,"object_types": object_types,"domain_description": domain_description,
        })
        return baml_py.BamlSyncStream[stream_types.ObjectsResult, types.ObjectsResult](
          result,
          lambda x: typing.cast(stream_types.ObjectsResult, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(types.ObjectsResult, x.cast_to(types, types, stream_types, False, __runtime__)),
          ctx,
        )
    def ExtractResume(self, resume: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlSyncStream[stream_types.Resume, types.Resume]:
        ctx, result = self.__options.merge_options(baml_options).create_sync_stream(function_name="ExtractResume", args={
            "resume": resume,
        })
        return baml_py.BamlSyncStream[stream_types.Resume, types.Resume](
          result,
          lambda x: typing.cast(stream_types.Resume, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(types.Resume, x.cast_to(types, types, stream_types, False, __runtime__)),
          ctx,
        )
    def GeneratePDDLDomainAzure(self, domain_description: str,object_nl: str,attributes_nl: str,actions_nl: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlSyncStream[stream_types.PDDLDomainResult, types.PDDLDomainResult]:
        ctx, result = self.__options.merge_options(baml_options).create_sync_stream(function_name="GeneratePDDLDomainAzure", args={
            "domain_description": domain_description,"object_nl": object_nl,"attributes_nl": attributes_nl,"actions_nl": actions_nl,
        })
        return baml_py.BamlSyncStream[stream_types.PDDLDomainResult, types.PDDLDomainResult](
          result,
          lambda x: typing.cast(stream_types.PDDLDomainResult, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(types.PDDLDomainResult, x.cast_to(types, types, stream_types, False, __runtime__)),
          ctx,
        )
    def GeneratePDDLDomainDeep(self, domain_description: str,object_nl: str,attributes_nl: str,actions_nl: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlSyncStream[stream_types.PDDLDomainResult, types.PDDLDomainResult]:
        ctx, result = self.__options.merge_options(baml_options).create_sync_stream(function_name="GeneratePDDLDomainDeep", args={
            "domain_description": domain_description,"object_nl": object_nl,"attributes_nl": attributes_nl,"actions_nl": actions_nl,
        })
        return baml_py.BamlSyncStream[stream_types.PDDLDomainResult, types.PDDLDomainResult](
          result,
          lambda x: typing.cast(stream_types.PDDLDomainResult, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(types.PDDLDomainResult, x.cast_to(types, types, stream_types, False, __runtime__)),
          ctx,
        )
    def GeneratePDDLDomainGemini(self, domain_description: str,object_nl: str,attributes_nl: str,actions_nl: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlSyncStream[stream_types.PDDLDomainResult, types.PDDLDomainResult]:
        ctx, result = self.__options.merge_options(baml_options).create_sync_stream(function_name="GeneratePDDLDomainGemini", args={
            "domain_description": domain_description,"object_nl": object_nl,"attributes_nl": attributes_nl,"actions_nl": actions_nl,
        })
        return baml_py.BamlSyncStream[stream_types.PDDLDomainResult, types.PDDLDomainResult](
          result,
          lambda x: typing.cast(stream_types.PDDLDomainResult, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(types.PDDLDomainResult, x.cast_to(types, types, stream_types, False, __runtime__)),
          ctx,
        )
    def GeneratePDDLProblemAzure(self, problem_description: str,domain_pddl_code: str,objects_baml: str,init_state_baml: str,goal_state_baml: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlSyncStream[stream_types.PDDLProblemResult, types.PDDLProblemResult]:
        ctx, result = self.__options.merge_options(baml_options).create_sync_stream(function_name="GeneratePDDLProblemAzure", args={
            "problem_description": problem_description,"domain_pddl_code": domain_pddl_code,"objects_baml": objects_baml,"init_state_baml": init_state_baml,"goal_state_baml": goal_state_baml,
        })
        return baml_py.BamlSyncStream[stream_types.PDDLProblemResult, types.PDDLProblemResult](
          result,
          lambda x: typing.cast(stream_types.PDDLProblemResult, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(types.PDDLProblemResult, x.cast_to(types, types, stream_types, False, __runtime__)),
          ctx,
        )
    def GeneratePDDLProblemDeep(self, problem_description: str,domain_pddl_code: str,objects_baml: str,init_state_baml: str,goal_state_baml: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlSyncStream[stream_types.PDDLProblemResult, types.PDDLProblemResult]:
        ctx, result = self.__options.merge_options(baml_options).create_sync_stream(function_name="GeneratePDDLProblemDeep", args={
            "problem_description": problem_description,"domain_pddl_code": domain_pddl_code,"objects_baml": objects_baml,"init_state_baml": init_state_baml,"goal_state_baml": goal_state_baml,
        })
        return baml_py.BamlSyncStream[stream_types.PDDLProblemResult, types.PDDLProblemResult](
          result,
          lambda x: typing.cast(stream_types.PDDLProblemResult, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(types.PDDLProblemResult, x.cast_to(types, types, stream_types, False, __runtime__)),
          ctx,
        )
    def GeneratePDDLProblemGemini(self, problem_description: str,domain_pddl_code: str,objects_baml: str,init_state_baml: str,goal_state_baml: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlSyncStream[stream_types.PDDLProblemResult, types.PDDLProblemResult]:
        ctx, result = self.__options.merge_options(baml_options).create_sync_stream(function_name="GeneratePDDLProblemGemini", args={
            "problem_description": problem_description,"domain_pddl_code": domain_pddl_code,"objects_baml": objects_baml,"init_state_baml": init_state_baml,"goal_state_baml": goal_state_baml,
        })
        return baml_py.BamlSyncStream[stream_types.PDDLProblemResult, types.PDDLProblemResult](
          result,
          lambda x: typing.cast(stream_types.PDDLProblemResult, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(types.PDDLProblemResult, x.cast_to(types, types, stream_types, False, __runtime__)),
          ctx,
        )
    def RefineAndAggregateDomainAzure(self, domain_description: str,object_types: str,attributes: str,actions_list: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlSyncStream[stream_types.RefinedActionsResult, types.RefinedActionsResult]:
        ctx, result = self.__options.merge_options(baml_options).create_sync_stream(function_name="RefineAndAggregateDomainAzure", args={
            "domain_description": domain_description,"object_types": object_types,"attributes": attributes,"actions_list": actions_list,
        })
        return baml_py.BamlSyncStream[stream_types.RefinedActionsResult, types.RefinedActionsResult](
          result,
          lambda x: typing.cast(stream_types.RefinedActionsResult, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(types.RefinedActionsResult, x.cast_to(types, types, stream_types, False, __runtime__)),
          ctx,
        )
    def RefineAndAggregateDomainDeep(self, domain_description: str,object_types: str,attributes: str,actions_list: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlSyncStream[stream_types.RefinedActionsResult, types.RefinedActionsResult]:
        ctx, result = self.__options.merge_options(baml_options).create_sync_stream(function_name="RefineAndAggregateDomainDeep", args={
            "domain_description": domain_description,"object_types": object_types,"attributes": attributes,"actions_list": actions_list,
        })
        return baml_py.BamlSyncStream[stream_types.RefinedActionsResult, types.RefinedActionsResult](
          result,
          lambda x: typing.cast(stream_types.RefinedActionsResult, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(types.RefinedActionsResult, x.cast_to(types, types, stream_types, False, __runtime__)),
          ctx,
        )
    def RefineAndAggregateDomainGemini(self, domain_description: str,object_types: str,attributes: str,actions_list: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlSyncStream[stream_types.RefinedActionsResult, types.RefinedActionsResult]:
        ctx, result = self.__options.merge_options(baml_options).create_sync_stream(function_name="RefineAndAggregateDomainGemini", args={
            "domain_description": domain_description,"object_types": object_types,"attributes": attributes,"actions_list": actions_list,
        })
        return baml_py.BamlSyncStream[stream_types.RefinedActionsResult, types.RefinedActionsResult](
          result,
          lambda x: typing.cast(stream_types.RefinedActionsResult, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(types.RefinedActionsResult, x.cast_to(types, types, stream_types, False, __runtime__)),
          ctx,
        )
    

class BamlHttpRequestClient:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    def ExtractActionsAzure(self, domain_description: str,object_types: str,object_attributes: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = self.__options.merge_options(baml_options).create_http_request_sync(function_name="ExtractActionsAzure", args={
            "domain_description": domain_description,"object_types": object_types,"object_attributes": object_attributes,
        }, mode="request")
        return result
    def ExtractActionsDeep(self, domain_description: str,object_types: str,object_attributes: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = self.__options.merge_options(baml_options).create_http_request_sync(function_name="ExtractActionsDeep", args={
            "domain_description": domain_description,"object_types": object_types,"object_attributes": object_attributes,
        }, mode="request")
        return result
    def ExtractActionsGemini(self, domain_description: str,object_types: str,object_attributes: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = self.__options.merge_options(baml_options).create_http_request_sync(function_name="ExtractActionsGemini", args={
            "domain_description": domain_description,"object_types": object_types,"object_attributes": object_attributes,
        }, mode="request")
        return result
    def ExtractAttributesAzure(self, object_types: str,domain_description: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = self.__options.merge_options(baml_options).create_http_request_sync(function_name="ExtractAttributesAzure", args={
            "object_types": object_types,"domain_description": domain_description,
        }, mode="request")
        return result
    def ExtractAttributesDeep(self, object_types: str,domain_description: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = self.__options.merge_options(baml_options).create_http_request_sync(function_name="ExtractAttributesDeep", args={
            "object_types": object_types,"domain_description": domain_description,
        }, mode="request")
        return result
    def ExtractAttributesGemini(self, object_types: str,domain_description: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = self.__options.merge_options(baml_options).create_http_request_sync(function_name="ExtractAttributesGemini", args={
            "object_types": object_types,"domain_description": domain_description,
        }, mode="request")
        return result
    def ExtractGoalAzure(self, problem_description: str,problem_objects: str,initial_state: str,domain_description: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = self.__options.merge_options(baml_options).create_http_request_sync(function_name="ExtractGoalAzure", args={
            "problem_description": problem_description,"problem_objects": problem_objects,"initial_state": initial_state,"domain_description": domain_description,
        }, mode="request")
        return result
    def ExtractGoalDeep(self, problem_description: str,problem_objects: str,initial_state: str,domain_description: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = self.__options.merge_options(baml_options).create_http_request_sync(function_name="ExtractGoalDeep", args={
            "problem_description": problem_description,"problem_objects": problem_objects,"initial_state": initial_state,"domain_description": domain_description,
        }, mode="request")
        return result
    def ExtractGoalGemini(self, problem_description: str,problem_objects: str,initial_state: str,domain_description: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = self.__options.merge_options(baml_options).create_http_request_sync(function_name="ExtractGoalGemini", args={
            "problem_description": problem_description,"problem_objects": problem_objects,"initial_state": initial_state,"domain_description": domain_description,
        }, mode="request")
        return result
    def ExtractInitialStateAzure(self, problem_description: str,problem_objects: str,object_attributes: str,domain_description: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = self.__options.merge_options(baml_options).create_http_request_sync(function_name="ExtractInitialStateAzure", args={
            "problem_description": problem_description,"problem_objects": problem_objects,"object_attributes": object_attributes,"domain_description": domain_description,
        }, mode="request")
        return result
    def ExtractInitialStateDeep(self, problem_description: str,problem_objects: str,object_attributes: str,domain_description: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = self.__options.merge_options(baml_options).create_http_request_sync(function_name="ExtractInitialStateDeep", args={
            "problem_description": problem_description,"problem_objects": problem_objects,"object_attributes": object_attributes,"domain_description": domain_description,
        }, mode="request")
        return result
    def ExtractInitialStateGemini(self, problem_description: str,problem_objects: str,object_attributes: str,domain_description: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = self.__options.merge_options(baml_options).create_http_request_sync(function_name="ExtractInitialStateGemini", args={
            "problem_description": problem_description,"problem_objects": problem_objects,"object_attributes": object_attributes,"domain_description": domain_description,
        }, mode="request")
        return result
    def ExtractObjectTypesAzure(self, domain_description: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = self.__options.merge_options(baml_options).create_http_request_sync(function_name="ExtractObjectTypesAzure", args={
            "domain_description": domain_description,
        }, mode="request")
        return result
    def ExtractObjectTypesDeep(self, domain_description: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = self.__options.merge_options(baml_options).create_http_request_sync(function_name="ExtractObjectTypesDeep", args={
            "domain_description": domain_description,
        }, mode="request")
        return result
    def ExtractObjectTypesGemini(self, domain_description: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = self.__options.merge_options(baml_options).create_http_request_sync(function_name="ExtractObjectTypesGemini", args={
            "domain_description": domain_description,
        }, mode="request")
        return result
    def ExtractProblemObjectsAzure(self, problem_description: str,object_types: str,domain_description: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = self.__options.merge_options(baml_options).create_http_request_sync(function_name="ExtractProblemObjectsAzure", args={
            "problem_description": problem_description,"object_types": object_types,"domain_description": domain_description,
        }, mode="request")
        return result
    def ExtractProblemObjectsDeep(self, problem_description: str,object_types: str,domain_description: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = self.__options.merge_options(baml_options).create_http_request_sync(function_name="ExtractProblemObjectsDeep", args={
            "problem_description": problem_description,"object_types": object_types,"domain_description": domain_description,
        }, mode="request")
        return result
    def ExtractProblemObjectsGemini(self, problem_description: str,object_types: str,domain_description: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = self.__options.merge_options(baml_options).create_http_request_sync(function_name="ExtractProblemObjectsGemini", args={
            "problem_description": problem_description,"object_types": object_types,"domain_description": domain_description,
        }, mode="request")
        return result
    def ExtractResume(self, resume: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = self.__options.merge_options(baml_options).create_http_request_sync(function_name="ExtractResume", args={
            "resume": resume,
        }, mode="request")
        return result
    def GeneratePDDLDomainAzure(self, domain_description: str,object_nl: str,attributes_nl: str,actions_nl: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = self.__options.merge_options(baml_options).create_http_request_sync(function_name="GeneratePDDLDomainAzure", args={
            "domain_description": domain_description,"object_nl": object_nl,"attributes_nl": attributes_nl,"actions_nl": actions_nl,
        }, mode="request")
        return result
    def GeneratePDDLDomainDeep(self, domain_description: str,object_nl: str,attributes_nl: str,actions_nl: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = self.__options.merge_options(baml_options).create_http_request_sync(function_name="GeneratePDDLDomainDeep", args={
            "domain_description": domain_description,"object_nl": object_nl,"attributes_nl": attributes_nl,"actions_nl": actions_nl,
        }, mode="request")
        return result
    def GeneratePDDLDomainGemini(self, domain_description: str,object_nl: str,attributes_nl: str,actions_nl: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = self.__options.merge_options(baml_options).create_http_request_sync(function_name="GeneratePDDLDomainGemini", args={
            "domain_description": domain_description,"object_nl": object_nl,"attributes_nl": attributes_nl,"actions_nl": actions_nl,
        }, mode="request")
        return result
    def GeneratePDDLProblemAzure(self, problem_description: str,domain_pddl_code: str,objects_baml: str,init_state_baml: str,goal_state_baml: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = self.__options.merge_options(baml_options).create_http_request_sync(function_name="GeneratePDDLProblemAzure", args={
            "problem_description": problem_description,"domain_pddl_code": domain_pddl_code,"objects_baml": objects_baml,"init_state_baml": init_state_baml,"goal_state_baml": goal_state_baml,
        }, mode="request")
        return result
    def GeneratePDDLProblemDeep(self, problem_description: str,domain_pddl_code: str,objects_baml: str,init_state_baml: str,goal_state_baml: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = self.__options.merge_options(baml_options).create_http_request_sync(function_name="GeneratePDDLProblemDeep", args={
            "problem_description": problem_description,"domain_pddl_code": domain_pddl_code,"objects_baml": objects_baml,"init_state_baml": init_state_baml,"goal_state_baml": goal_state_baml,
        }, mode="request")
        return result
    def GeneratePDDLProblemGemini(self, problem_description: str,domain_pddl_code: str,objects_baml: str,init_state_baml: str,goal_state_baml: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = self.__options.merge_options(baml_options).create_http_request_sync(function_name="GeneratePDDLProblemGemini", args={
            "problem_description": problem_description,"domain_pddl_code": domain_pddl_code,"objects_baml": objects_baml,"init_state_baml": init_state_baml,"goal_state_baml": goal_state_baml,
        }, mode="request")
        return result
    def RefineAndAggregateDomainAzure(self, domain_description: str,object_types: str,attributes: str,actions_list: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = self.__options.merge_options(baml_options).create_http_request_sync(function_name="RefineAndAggregateDomainAzure", args={
            "domain_description": domain_description,"object_types": object_types,"attributes": attributes,"actions_list": actions_list,
        }, mode="request")
        return result
    def RefineAndAggregateDomainDeep(self, domain_description: str,object_types: str,attributes: str,actions_list: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = self.__options.merge_options(baml_options).create_http_request_sync(function_name="RefineAndAggregateDomainDeep", args={
            "domain_description": domain_description,"object_types": object_types,"attributes": attributes,"actions_list": actions_list,
        }, mode="request")
        return result
    def RefineAndAggregateDomainGemini(self, domain_description: str,object_types: str,attributes: str,actions_list: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = self.__options.merge_options(baml_options).create_http_request_sync(function_name="RefineAndAggregateDomainGemini", args={
            "domain_description": domain_description,"object_types": object_types,"attributes": attributes,"actions_list": actions_list,
        }, mode="request")
        return result
    

class BamlHttpStreamRequestClient:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    def ExtractActionsAzure(self, domain_description: str,object_types: str,object_attributes: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = self.__options.merge_options(baml_options).create_http_request_sync(function_name="ExtractActionsAzure", args={
            "domain_description": domain_description,"object_types": object_types,"object_attributes": object_attributes,
        }, mode="stream")
        return result
    def ExtractActionsDeep(self, domain_description: str,object_types: str,object_attributes: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = self.__options.merge_options(baml_options).create_http_request_sync(function_name="ExtractActionsDeep", args={
            "domain_description": domain_description,"object_types": object_types,"object_attributes": object_attributes,
        }, mode="stream")
        return result
    def ExtractActionsGemini(self, domain_description: str,object_types: str,object_attributes: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = self.__options.merge_options(baml_options).create_http_request_sync(function_name="ExtractActionsGemini", args={
            "domain_description": domain_description,"object_types": object_types,"object_attributes": object_attributes,
        }, mode="stream")
        return result
    def ExtractAttributesAzure(self, object_types: str,domain_description: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = self.__options.merge_options(baml_options).create_http_request_sync(function_name="ExtractAttributesAzure", args={
            "object_types": object_types,"domain_description": domain_description,
        }, mode="stream")
        return result
    def ExtractAttributesDeep(self, object_types: str,domain_description: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = self.__options.merge_options(baml_options).create_http_request_sync(function_name="ExtractAttributesDeep", args={
            "object_types": object_types,"domain_description": domain_description,
        }, mode="stream")
        return result
    def ExtractAttributesGemini(self, object_types: str,domain_description: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = self.__options.merge_options(baml_options).create_http_request_sync(function_name="ExtractAttributesGemini", args={
            "object_types": object_types,"domain_description": domain_description,
        }, mode="stream")
        return result
    def ExtractGoalAzure(self, problem_description: str,problem_objects: str,initial_state: str,domain_description: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = self.__options.merge_options(baml_options).create_http_request_sync(function_name="ExtractGoalAzure", args={
            "problem_description": problem_description,"problem_objects": problem_objects,"initial_state": initial_state,"domain_description": domain_description,
        }, mode="stream")
        return result
    def ExtractGoalDeep(self, problem_description: str,problem_objects: str,initial_state: str,domain_description: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = self.__options.merge_options(baml_options).create_http_request_sync(function_name="ExtractGoalDeep", args={
            "problem_description": problem_description,"problem_objects": problem_objects,"initial_state": initial_state,"domain_description": domain_description,
        }, mode="stream")
        return result
    def ExtractGoalGemini(self, problem_description: str,problem_objects: str,initial_state: str,domain_description: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = self.__options.merge_options(baml_options).create_http_request_sync(function_name="ExtractGoalGemini", args={
            "problem_description": problem_description,"problem_objects": problem_objects,"initial_state": initial_state,"domain_description": domain_description,
        }, mode="stream")
        return result
    def ExtractInitialStateAzure(self, problem_description: str,problem_objects: str,object_attributes: str,domain_description: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = self.__options.merge_options(baml_options).create_http_request_sync(function_name="ExtractInitialStateAzure", args={
            "problem_description": problem_description,"problem_objects": problem_objects,"object_attributes": object_attributes,"domain_description": domain_description,
        }, mode="stream")
        return result
    def ExtractInitialStateDeep(self, problem_description: str,problem_objects: str,object_attributes: str,domain_description: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = self.__options.merge_options(baml_options).create_http_request_sync(function_name="ExtractInitialStateDeep", args={
            "problem_description": problem_description,"problem_objects": problem_objects,"object_attributes": object_attributes,"domain_description": domain_description,
        }, mode="stream")
        return result
    def ExtractInitialStateGemini(self, problem_description: str,problem_objects: str,object_attributes: str,domain_description: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = self.__options.merge_options(baml_options).create_http_request_sync(function_name="ExtractInitialStateGemini", args={
            "problem_description": problem_description,"problem_objects": problem_objects,"object_attributes": object_attributes,"domain_description": domain_description,
        }, mode="stream")
        return result
    def ExtractObjectTypesAzure(self, domain_description: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = self.__options.merge_options(baml_options).create_http_request_sync(function_name="ExtractObjectTypesAzure", args={
            "domain_description": domain_description,
        }, mode="stream")
        return result
    def ExtractObjectTypesDeep(self, domain_description: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = self.__options.merge_options(baml_options).create_http_request_sync(function_name="ExtractObjectTypesDeep", args={
            "domain_description": domain_description,
        }, mode="stream")
        return result
    def ExtractObjectTypesGemini(self, domain_description: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = self.__options.merge_options(baml_options).create_http_request_sync(function_name="ExtractObjectTypesGemini", args={
            "domain_description": domain_description,
        }, mode="stream")
        return result
    def ExtractProblemObjectsAzure(self, problem_description: str,object_types: str,domain_description: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = self.__options.merge_options(baml_options).create_http_request_sync(function_name="ExtractProblemObjectsAzure", args={
            "problem_description": problem_description,"object_types": object_types,"domain_description": domain_description,
        }, mode="stream")
        return result
    def ExtractProblemObjectsDeep(self, problem_description: str,object_types: str,domain_description: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = self.__options.merge_options(baml_options).create_http_request_sync(function_name="ExtractProblemObjectsDeep", args={
            "problem_description": problem_description,"object_types": object_types,"domain_description": domain_description,
        }, mode="stream")
        return result
    def ExtractProblemObjectsGemini(self, problem_description: str,object_types: str,domain_description: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = self.__options.merge_options(baml_options).create_http_request_sync(function_name="ExtractProblemObjectsGemini", args={
            "problem_description": problem_description,"object_types": object_types,"domain_description": domain_description,
        }, mode="stream")
        return result
    def ExtractResume(self, resume: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = self.__options.merge_options(baml_options).create_http_request_sync(function_name="ExtractResume", args={
            "resume": resume,
        }, mode="stream")
        return result
    def GeneratePDDLDomainAzure(self, domain_description: str,object_nl: str,attributes_nl: str,actions_nl: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = self.__options.merge_options(baml_options).create_http_request_sync(function_name="GeneratePDDLDomainAzure", args={
            "domain_description": domain_description,"object_nl": object_nl,"attributes_nl": attributes_nl,"actions_nl": actions_nl,
        }, mode="stream")
        return result
    def GeneratePDDLDomainDeep(self, domain_description: str,object_nl: str,attributes_nl: str,actions_nl: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = self.__options.merge_options(baml_options).create_http_request_sync(function_name="GeneratePDDLDomainDeep", args={
            "domain_description": domain_description,"object_nl": object_nl,"attributes_nl": attributes_nl,"actions_nl": actions_nl,
        }, mode="stream")
        return result
    def GeneratePDDLDomainGemini(self, domain_description: str,object_nl: str,attributes_nl: str,actions_nl: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = self.__options.merge_options(baml_options).create_http_request_sync(function_name="GeneratePDDLDomainGemini", args={
            "domain_description": domain_description,"object_nl": object_nl,"attributes_nl": attributes_nl,"actions_nl": actions_nl,
        }, mode="stream")
        return result
    def GeneratePDDLProblemAzure(self, problem_description: str,domain_pddl_code: str,objects_baml: str,init_state_baml: str,goal_state_baml: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = self.__options.merge_options(baml_options).create_http_request_sync(function_name="GeneratePDDLProblemAzure", args={
            "problem_description": problem_description,"domain_pddl_code": domain_pddl_code,"objects_baml": objects_baml,"init_state_baml": init_state_baml,"goal_state_baml": goal_state_baml,
        }, mode="stream")
        return result
    def GeneratePDDLProblemDeep(self, problem_description: str,domain_pddl_code: str,objects_baml: str,init_state_baml: str,goal_state_baml: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = self.__options.merge_options(baml_options).create_http_request_sync(function_name="GeneratePDDLProblemDeep", args={
            "problem_description": problem_description,"domain_pddl_code": domain_pddl_code,"objects_baml": objects_baml,"init_state_baml": init_state_baml,"goal_state_baml": goal_state_baml,
        }, mode="stream")
        return result
    def GeneratePDDLProblemGemini(self, problem_description: str,domain_pddl_code: str,objects_baml: str,init_state_baml: str,goal_state_baml: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = self.__options.merge_options(baml_options).create_http_request_sync(function_name="GeneratePDDLProblemGemini", args={
            "problem_description": problem_description,"domain_pddl_code": domain_pddl_code,"objects_baml": objects_baml,"init_state_baml": init_state_baml,"goal_state_baml": goal_state_baml,
        }, mode="stream")
        return result
    def RefineAndAggregateDomainAzure(self, domain_description: str,object_types: str,attributes: str,actions_list: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = self.__options.merge_options(baml_options).create_http_request_sync(function_name="RefineAndAggregateDomainAzure", args={
            "domain_description": domain_description,"object_types": object_types,"attributes": attributes,"actions_list": actions_list,
        }, mode="stream")
        return result
    def RefineAndAggregateDomainDeep(self, domain_description: str,object_types: str,attributes: str,actions_list: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = self.__options.merge_options(baml_options).create_http_request_sync(function_name="RefineAndAggregateDomainDeep", args={
            "domain_description": domain_description,"object_types": object_types,"attributes": attributes,"actions_list": actions_list,
        }, mode="stream")
        return result
    def RefineAndAggregateDomainGemini(self, domain_description: str,object_types: str,attributes: str,actions_list: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = self.__options.merge_options(baml_options).create_http_request_sync(function_name="RefineAndAggregateDomainGemini", args={
            "domain_description": domain_description,"object_types": object_types,"attributes": attributes,"actions_list": actions_list,
        }, mode="stream")
        return result
    

b = BamlSyncClient(DoNotUseDirectlyCallManager({}))