# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions
from enum import Enum


from pydantic import BaseModel, ConfigDict


import baml_py

CheckT = typing_extensions.TypeVar('CheckT')
CheckName = typing_extensions.TypeVar('CheckName', bound=str)

class Check(BaseModel):
    name: str
    expression: str
    status: str
class Checked(BaseModel, typing.Generic[CheckT, CheckName]):
    value: CheckT
    checks: typing.Dict[CheckName, Check]

def get_checks(checks: typing.Dict[CheckName, Check]) -> typing.List[Check]:
    return list(checks.values())

def all_succeeded(checks: typing.Dict[CheckName, Check]) -> bool:
    return all(check.status == "succeeded" for check in get_checks(checks))
# #########################################################################
# Generated enums (0)
# #########################################################################

# #########################################################################
# Generated classes (23)
# #########################################################################

class Action(BaseModel):
    name: str
    actor: str
    parameters: typing.List["Parameters"]
    preconditions: typing.List["Precondition"]
    effects: typing.List["Effect"]
    description: typing.Optional[str] = None

class ActionsResult(BaseModel):
    actions: typing.List["Action"]

class Attribute(BaseModel):
    name: str
    type: str
    description: typing.Optional[str] = None

class AttributesResult(BaseModel):
    types_with_attributes: typing.List["TypeAttributes"]

class Effect(BaseModel):
    attribute: str
    change: str

class GoalCondition(BaseModel):
    object_name: str
    attribute: str
    required_value: str
    explanation: typing.Optional[str] = None

class GoalRelation(BaseModel):
    relation_type: str
    object1: str
    object2: str
    explanation: typing.Optional[str] = None

class GoalResult(BaseModel):
    conditions: typing.List["GoalCondition"]
    relations: typing.List["GoalRelation"]
    goal_summary: str

class InitialFact(BaseModel):
    object_name: str
    attribute: str
    value: str
    explanation: typing.Optional[str] = None

class InitialRelation(BaseModel):
    relation_type: str
    object1: str
    object2: str
    explanation: typing.Optional[str] = None

class InitialStateResult(BaseModel):
    facts: typing.List["InitialFact"]
    relations: typing.List["InitialRelation"]

class ObjectTypeHierarchy(BaseModel):
    name: str
    parent_type: typing.Optional[str] = None
    description: typing.Optional[str] = None

class ObjectTypesResult(BaseModel):
    types: typing.List["ObjectTypeHierarchy"]

class ObjectsResult(BaseModel):
    objects: typing.List["ProblemObject"]

class PDDLDomainResult(BaseModel):
    domain_name: str
    pddl_code: str
    explanation: typing.Optional[str] = None

class PDDLProblemResult(BaseModel):
    problem_name: str
    domain_name: str
    pddl_code: str
    explanation: typing.Optional[str] = None

class Parameters(BaseModel):
    name: str
    type: str

class Precondition(BaseModel):
    attribute: str
    condition: str

class ProblemObject(BaseModel):
    name: str
    type: str
    description: typing.Optional[str] = None

class RefinedAction(BaseModel):
    name: str
    description: str
    actor: str
    parameters: typing.List["Parameters"]
    preconditions: typing.List["Precondition"]
    effects: typing.List["Effect"]
    requires_adl: str

class RefinedActionsResult(BaseModel):
    actions: typing.List["RefinedAction"]

class Resume(BaseModel):
    name: str
    email: str
    experience: typing.List[str]
    skills: typing.List[str]

class TypeAttributes(BaseModel):
    type_name: str
    attributes: typing.List["Attribute"]

# #########################################################################
# Generated type aliases (0)
# #########################################################################
