# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

from . import types
from . import stream_types


type_map = {

    "types.Action": types.Action,
    "stream_types.Action": stream_types.Action,

    "types.ActionsResult": types.ActionsResult,
    "stream_types.ActionsResult": stream_types.ActionsResult,

    "types.Attribute": types.Attribute,
    "stream_types.Attribute": stream_types.Attribute,

    "types.AttributesResult": types.AttributesResult,
    "stream_types.AttributesResult": stream_types.AttributesResult,

    "types.Effect": types.Effect,
    "stream_types.Effect": stream_types.Effect,

    "types.GoalCondition": types.GoalCondition,
    "stream_types.GoalCondition": stream_types.GoalCondition,

    "types.GoalRelation": types.GoalRelation,
    "stream_types.GoalRelation": stream_types.GoalRelation,

    "types.GoalResult": types.GoalResult,
    "stream_types.GoalResult": stream_types.GoalResult,

    "types.InitialFact": types.InitialFact,
    "stream_types.InitialFact": stream_types.InitialFact,

    "types.InitialRelation": types.InitialRelation,
    "stream_types.InitialRelation": stream_types.InitialRelation,

    "types.InitialStateResult": types.InitialStateResult,
    "stream_types.InitialStateResult": stream_types.InitialStateResult,

    "types.ObjectTypeHierarchy": types.ObjectTypeHierarchy,
    "stream_types.ObjectTypeHierarchy": stream_types.ObjectTypeHierarchy,

    "types.ObjectTypesResult": types.ObjectTypesResult,
    "stream_types.ObjectTypesResult": stream_types.ObjectTypesResult,

    "types.ObjectsResult": types.ObjectsResult,
    "stream_types.ObjectsResult": stream_types.ObjectsResult,

    "types.PDDLDomainResult": types.PDDLDomainResult,
    "stream_types.PDDLDomainResult": stream_types.PDDLDomainResult,

    "types.PDDLProblemResult": types.PDDLProblemResult,
    "stream_types.PDDLProblemResult": stream_types.PDDLProblemResult,

    "types.Parameters": types.Parameters,
    "stream_types.Parameters": stream_types.Parameters,

    "types.Precondition": types.Precondition,
    "stream_types.Precondition": stream_types.Precondition,

    "types.ProblemObject": types.ProblemObject,
    "stream_types.ProblemObject": stream_types.ProblemObject,

    "types.RefinedAction": types.RefinedAction,
    "stream_types.RefinedAction": stream_types.RefinedAction,

    "types.RefinedActionsResult": types.RefinedActionsResult,
    "stream_types.RefinedActionsResult": stream_types.RefinedActionsResult,

    "types.Resume": types.Resume,
    "stream_types.Resume": stream_types.Resume,

    "types.TypeAttributes": types.TypeAttributes,
    "stream_types.TypeAttributes": stream_types.TypeAttributes,


}